### ISSUE TITLE
Don't change case of schema properties

### ISSUE THREAD

**Issue by d9k** [Ryan-Sin/swagger-nestjs-codegen#12]
# Input

```
# . . . . .

components:
  schemas:
    MyItem:

# . . . . .

      updated_at: 
          type: string
          format: date-time
          nullable: true

# . . . . .
```

# Ouput to `src/dto/data/my-item.data.ts`

```
// . . . . .

  @ApiProperty({
    description: '',
    required: false,
  })
  @IsOptional()
  @IsString()
  updatedAt?: string;

// . . . . .
```

# Expected ouput to `src/dto/data/my-item.data.ts`

```
// . . . . .

  @ApiProperty({
    description: '',
    required: false,
  })
  @IsOptional()
  @IsString()
  updated_at?: string;

// . . . . .
```

# Reason

Sometimes it is a business requirement to have snake_case properties names for JSON body/JSON response.
