### ISSUE TITLE
code for integer type

### ISSUE THREAD

**Issue by d9k** [Ryan-Sin/swagger-nestjs-codegen#7]
input

```
components:
   my_item:
      type: object
      properties:
        id:
          type: integer
```

output:

```
export class MyItemDto {
  @ApiProperty({
    description: '',
    required: false,
  })
  @IsOptional()
  @IsNumber()
  id?: integer;
```

`integer` is not a valid type name in typescript.
